In [2]:
import pandas as pd
import pymongo

df = pd.read_csv('data.csv')
df.sample(5)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
166399,166400,Female,44,1,28.0,0,1-2 Year,Yes,39243.0,26.0,152,0
170820,170821,Female,40,1,28.0,1,1-2 Year,No,38490.0,31.0,122,0
313745,313746,Male,40,1,41.0,0,1-2 Year,Yes,22197.0,26.0,35,0
301163,301164,Female,26,1,30.0,1,1-2 Year,No,33244.0,124.0,221,0
337235,337236,Male,25,1,45.0,0,< 1 Year,Yes,22488.0,160.0,184,0

In [5]:
# df should be converted into dict before we push it to mongodb

data = df.to_dict(orient='records')
# data

In [10]:
import os
from dotenv import load_dotenv

load_dotenv()

DB_NAME = os.getenv("DB_NAME") # logical database inside the cluster
COLLECTION_NAME = os.getenv("COLLECTION_NAME") # table-like container
CONNECTION_URL = os.getenv("CONNECTION_URL") # how Python finds & authenticates to MongoDB

In [11]:
client = pymongo.MongoClient(CONNECTION_URL)
# This does not immediately connect.
# It creates a connection manager that:
# Handles pooling
# Handles authentication
# Handles failover internally
data_base = client[DB_NAME]
# This does not create the database yet
# It creates a reference to Proj1
collection = data_base[COLLECTION_NAME]
# Again, no creation yet
# Just a logical reference to Proj1-Data

# project -> database -> collection -> document -> record -> field -> value -> character -> byte -> bit -> electron -> quark -> string theory -> multiverse -> etc -> infinity -> beyond -> to be continued...

In [ ]:
# Uploading data to MongoDB
rec = collection.insert_many(data)
# This is the moment when everything becomes real.

# What happens internally:
# MongoDB creates database Proj1 (if not exists)
# Creates collection Proj1-Data (if not exists)
# Inserts each dictionary in data as a document
# Automatically adds _id field to each document
# Returns inserted IDs inside rec

In [13]:
# Load back data from mongodb

df = pd.DataFrame(list(collection.find().limit(100)))
df.head(2)

,_id,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,6954d1b730ab97559adcef81,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,6954d1b730ab97559adcef82,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0

In [ ]:
# cursor = collection.find().batch_size(50)

# rows = []
# for doc in cursor:
#     rows.append(doc)
#     if len(rows) >= 100:
#         break

# df = pd.DataFrame(rows)